In [152]:
import numpy as np
from itertools import combinations, chain
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

def powerset(iterable):
    "powerset([1,2,3]) --> () (1,) (2,) (3,) (1,2) (1,3) (2,3) (1,2,3)"
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [123]:

parameter_set = {
    'sigma': {
        'values': np.array([1e-1, 5e-1, 1, 3, 6]),
        'prior': np.array([0.1, 0.2, 0.5, 0.1, 0.1]),
        'type': 'not_link'
    },
    'theta': {
        'values': np.array([1/4, 1/2, 1, 3]),
        'prior': np.array([0.1, 0.2, 0.5, 0.1, 0.1]),
        'type': 'not_link'
    },
    '0->1': {
        'values': np.array([-1, -1/2, 0, 1/2, 1]),
        'prior': np.array([0.05, 0.3, 0.4, 0.1, 0.05]),
        'type': 'link'
    },
    '0->2': {
        'values': np.array([-1, -1/2, 0, 1/2, 1]),
        'prior': np.array([0.05, 0.3, 0.4, 0.1, 0.05]),
        'type': 'link'
    },
    '1->0': {
        'values': np.array([-1, -1/2, 0, 1/2, 1]),
        'prior': np.array([0.05, 0.3, 0.4, 0.1, 0.05]),
        'type': 'link'
    },
    '1->2': {
        'values': np.array([-1, -1/2, 0, 1/2, 1]),
        'prior': np.array([0.05, 0.3, 0.4, 0.1, 0.05]),
        'type': 'link'
    },
    '2->0': {
        'values': np.array([-1, -1/2, 0, 1/2, 1]),
        'prior': np.array([0.05, 0.3, 0.4, 0.1, 0.05]),
        'type': 'link'
    },
    '2->1': {
        'values': np.array([-1, -1/2, 0, 1/2, 1]),
        'prior': np.array([0.05, 0.3, 0.4, 0.1, 0.05]),
        'type': 'link'
    }
}

In [18]:
parameter_set

{'sigma': {'values': array([0.1, 0.5, 1. , 3. , 6. ]),
  'prior': array([0.1, 0.2, 0.5, 0.1, 0.1]),
  'type': 'not_link'},
 '0->1': {'values': array([-1. , -0.5,  0. ,  0.5,  1. ]),
  'prior': array([0.05, 0.3 , 0.4 , 0.1 , 0.05]),
  'type': 'link'}}

In [27]:
K = 3

G = np.empty((K, K), dtype=object)
for i in range(K):
    for j in range(K):
        if i == j:
            G[i, j] = ''
        else:
            G[i, j] = f'{i}->{j}'

G

array([['', '0->1', '0->2'],
       ['1->0', '', '1->2'],
       ['2->0', '2->1', '']], dtype=object)

In [96]:
names = [p_n for p_n in parameter_set.keys()]
a = np.array(names, dtype=object)

b = np.array([0, 1, 0], dtype=bool)

",".join(a)

'sigma,0->1,0->2'

In [109]:
links = np.array([-1, 1])

dependencies = ['sigma', '0->1', '0->2']
values = [parameter_set[dep]['values'] for dep in dependencies]
num_values = np.array([v.size for v in values])

c = len(dependencies) # Number of parameters (columns)
r = num_values.prod() # Number of tuples (rows)
S = np.zeros((r, c))
for i in range(c):
    tile_coef = int(num_values[i+1:].prod())
    rep_coef = int(num_values[:i].prod())
    ou = np.tile(values[i], (int(tile_coef), 1)).flatten('F')
    #os = tuple(ou for _ in range(rep_coef))
    #o = np.concatenate(os)

    o = ou[np.tile(np.arange(ou.size), (1, rep_coef)).flatten()]
    S[:, i] = o.T

S

array([[ 0.1, -1. , -1. ],
       [ 0.1, -1. , -0.5],
       [ 0.1, -1. ,  0. ],
       [ 0.1, -1. ,  0.5],
       [ 0.1, -1. ,  1. ],
       [ 0.1, -0.5, -1. ],
       [ 0.1, -0.5, -0.5],
       [ 0.1, -0.5,  0. ],
       [ 0.1, -0.5,  0.5],
       [ 0.1, -0.5,  1. ],
       [ 0.1,  0. , -1. ],
       [ 0.1,  0. , -0.5],
       [ 0.1,  0. ,  0. ],
       [ 0.1,  0. ,  0.5],
       [ 0.1,  0. ,  1. ],
       [ 0.1,  0.5, -1. ],
       [ 0.1,  0.5, -0.5],
       [ 0.1,  0.5,  0. ],
       [ 0.1,  0.5,  0.5],
       [ 0.1,  0.5,  1. ],
       [ 0.1,  1. , -1. ],
       [ 0.1,  1. , -0.5],
       [ 0.1,  1. ,  0. ],
       [ 0.1,  1. ,  0.5],
       [ 0.1,  1. ,  1. ],
       [ 0.5, -1. , -1. ],
       [ 0.5, -1. , -0.5],
       [ 0.5, -1. ,  0. ],
       [ 0.5, -1. ,  0.5],
       [ 0.5, -1. ,  1. ],
       [ 0.5, -0.5, -1. ],
       [ 0.5, -0.5, -0.5],
       [ 0.5, -0.5,  0. ],
       [ 0.5, -0.5,  0.5],
       [ 0.5, -0.5,  1. ],
       [ 0.5,  0. , -1. ],
       [ 0.5,  0. , -0.5],
 

In [92]:
dependencies = ['sigma', 'theta', '0->1', '0->2', '1->0', '1->2', '2->0', '2->1']
no_links = ['sigma', 'theta']
links = ['0->1', '0->2', '1->0', '1->2', '2->0', '2->1']


K = 3

subsets = {}

# Links
for k in links:
    sub = no_links + [k]
    subsets[','.join(sub)] = None

# Interventions
for nl in no_links:
    sub = [nl] + links
    subsets[','.join(sub)] = None
    for a in range(K):
        sub = [nl] + np.delete(G[a, :], a).tolist()
        subsets[','.join(sub)] = None

subsets

{'sigma,theta,0->1': None,
 'sigma,theta,0->2': None,
 'sigma,theta,1->0': None,
 'sigma,theta,1->2': None,
 'sigma,theta,2->0': None,
 'sigma,theta,2->1': None,
 'sigma,0->1,0->2,1->0,1->2,2->0,2->1': None,
 'sigma,0->1,0->2': None,
 'sigma,1->0,1->2': None,
 'sigma,2->0,2->1': None,
 'theta,0->1,0->2,1->0,1->2,2->0,2->1': None,
 'theta,0->1,0->2': None,
 'theta,1->0,1->2': None,
 'theta,2->0,2->1': None}

In [121]:
a = np.array([-1, 1])
K = 3
c = len(links)
s = K**2 - K
S = np.zeros((c**s, s))
for i in range(s):
    ou = np.tile(a, (int(c**(s-i-1)), 1)).flatten('F')
    os = tuple(ou for _ in range(c**i))
    #print(os)
    #print()
    o = np.concatenate(os)
    S[:, i] = o.T

S

array([[-1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.,  1.],
       [-1., -1., -1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1.,  1.],
       [-1., -1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1.,  1.],
       [-1., -1., -1.,  1.,  1., -1.],
       [-1., -1., -1.,  1.,  1.,  1.],
       [-1., -1.,  1., -1., -1., -1.],
       [-1., -1.,  1., -1., -1.,  1.],
       [-1., -1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.,  1.],
       [-1., -1.,  1.,  1., -1., -1.],
       [-1., -1.,  1.,  1., -1.,  1.],
       [-1., -1.,  1.,  1.,  1., -1.],
       [-1., -1.,  1.,  1.,  1.,  1.],
       [-1.,  1., -1., -1., -1., -1.],
       [-1.,  1., -1., -1., -1.,  1.],
       [-1.,  1., -1., -1.,  1., -1.],
       [-1.,  1., -1., -1.,  1.,  1.],
       [-1.,  1., -1.,  1., -1., -1.],
       [-1.,  1., -1.,  1., -1.,  1.],
       [-1.,  1., -1.,  1.,  1., -1.],
       [-1.,  1., -1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1., -1., -1.],
       [-1.,  1.,  1., -1

In [110]:
a = np.array([0.2, 0.1, 0, 0.5, 0.2])

b = np.array([0, 1, 2, 3, 4])

c = np.tile(b, (1, 2))
a[b]
c
a[c]

array([[0.2, 0.1, 0. , 0.5, 0.2, 0.2, 0.1, 0. , 0.5, 0.2]])

In [118]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype=object)

b = np.array(['b', 'e', 'g'], dtype=object)

c = np.in1d(a, b)

d = np.zeros(a.size)

d[c] = 1

d

array([0., 1., 0., 0., 1., 0., 1.])

In [126]:
def _construct_parameter_combinations(param_labels, param_values):
    num_values = np.array([p_v.size for p_v in param_values])
    c = len(param_labels) # Number of parameters (columns)
    r = num_values.prod() # Number of tuples (rows)
    S = np.zeros((r, c))
    for i in range(c):
        tile_coef = int(num_values[i+1:].prod())
        rep_coef = int(num_values[:i].prod())
        ou = np.tile(param_values[i], (int(tile_coef), 1)).flatten('F')
        o = ou[np.tile(np.arange(ou.size), (1, rep_coef)).flatten()]
        S[:, i] = o.T
    return S

names = ['sigma', 'theta', '0->1', '2->1']
values = [parameter_set[name]['values'] for name in names]

values_space = _construct_parameter_combinations(names, values)

values_space.shape

(500, 4)

In [249]:
belief_values = np.array([-1, -1/2, 0, 1/2, 1])
X = np.array([50, -23, -1])
X_prev = np.array([42, -21, 4])
dt = 1/5 

names = ['sigma', 'theta', '0->1']
values = [parameter_set[name]['values'] for name in names]
values_space = _construct_parameter_combinations(names, values)

belief = '2->1'
belief_values = parameter_set[belief]['values']

to_consider = np.array([0, 1, 0]).astype(bool)
K = to_consider.size

out = np.zeros((belief_values.size, values_space.shape[0]))
for k in range(K):
    if to_consider[k] == 0:
        continue

    current_var = np.zeros(K).astype(bool)
    current_var[k] = 1

    sigmas = values_space[:, names.index('sigma')]

    thetas = values_space[:, names.index('theta')]

    links = np.ones((belief_values.size, K, values_space.shape[0]))
    print(links.shape)
    links[:, ~current_var, :] = np.tile(values_space[:, 2:], (belief_values.size, 1, 1)).reshape((belief_values.size, values_space[:, 2:].shape[1], values_space[:, 2:].shape[0]))
    bvs = np.tile(belief_values, (values_space[:, 2:].shape[0], 1)).T
    links[:, int(belief[0]), :] = bvs

    regularisor = - X_prev[k] * (np.abs(X_prev[k]) / 100)
    X_prev_tiled = X_prev#np.tile(X_prev, (belief_values.size, 1))
    mus = thetas * (X_prev_tiled @ links + regularisor - X_prev[k]) * dt

    out += stats.norm.logpdf(X[k], loc=mus, scale=sigmas) 

(5, 3, 100)


In [251]:
belief_values = np.array([-1, -1/2, 0, 1/2, 1])
X = np.array([50, -23, -1])
X_prev = np.array([42, -21, 4])
dt = 1/5 

names = ['sigma', '0->1', '2->1']
values = [parameter_set[name]['values'] for name in names]
values_space = _construct_parameter_combinations(names, values)

belief = 'theta'
belief_values = parameter_set[belief]['values']

to_consider = np.array([0, 1, 0]).astype(bool)
K = to_consider.size

out = np.zeros((belief_values.size, values_space.shape[0]))
for k in range(K):
    if to_consider[k] == 0:
        continue
    
    # Current variable k as array
    current_var = np.zeros(K).astype(bool)
    current_var[k] = 1
    # Current indices of links to build the link matrix
    ## WORK HERE

    sigmas = values_space[:, names.index('sigma')]

    thetas = np.tile(belief_values, (values_space.shape[0], 1))

    links = np.ones((belief_values.size, K, values_space.shape[0]))
    print(links.shape)
    links[:, ~current_var, :] = np.tile(values_space[:, 2:], (belief_values.size, 1, 1)).reshape((belief_values.size, values_space[:, 2:].shape[1], values_space[:, 2:].shape[0]))
    bvs = np.tile(belief_values, (values_space[:, 2:].shape[0], 1)).T
    links[:, int(belief[0]), :] = bvs

    regularisor = - X_prev[k] * (np.abs(X_prev[k]) / 100)
    X_prev_tiled = X_prev#np.tile(X_prev, (belief_values.size, 1))
    mus = thetas * (X_prev_tiled @ links + regularisor - X_prev[k]) * dt

    out += stats.norm.logpdf(X[k], loc=mus, scale=sigmas) 

(4, 3, 125)


ValueError: invalid literal for int() with base 10: 't'

In [237]:
print(links.shape)
print(X_prev_tiled.shape)
print((X_prev_tiled @ links).shape)

(5, 3, 100)
(3,)
(5, 100)


In [243]:
out

array([[-2.18819824e+04, -2.41337599e+04, -2.64957874e+04,
        -2.89680649e+04, -3.15505924e+04, -1.77477804e+04,
        -2.19248904e+04, -2.65430004e+04, -3.16021104e+04,
        -3.71022204e+04, -1.07766726e+04, -1.78251126e+04,
        -2.66375526e+04, -3.72139926e+04, -4.95544326e+04,
        -1.89522153e+02, -5.66548215e+03, -2.70174422e+04,
        -6.42454022e+04, -1.17349362e+05, -8.75560432e+02,
        -9.65631532e+02, -1.06011263e+03, -1.15900373e+03,
        -1.26230483e+03, -7.10192353e+02, -8.77276753e+02,
        -1.06200115e+03, -1.26436555e+03, -1.48436995e+03,
        -4.31348039e+02, -7.13285639e+02, -1.06578324e+03,
        -1.48884084e+03, -1.98245844e+03, -7.86202335e+00,
        -2.26900423e+02, -1.08097882e+03, -2.57009722e+03,
        -4.69425562e+03, -2.19752599e+02, -2.42270374e+02,
        -2.65890649e+02, -2.90613424e+02, -3.16438699e+02,
        -1.78410579e+02, -2.20181679e+02, -2.66362779e+02,
        -3.16953879e+02, -3.71954979e+02, -1.08699501e+0

In [241]:
X_prev

array([ 42, -21,   4])

In [240]:
X_prev_tiled @ links

array([[-67., -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,  17., -67.,
        -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,  17., -67., -46.,
        -25.,  -4.,  17., -67., -46., -25.,  -4.,  17., -67., -46., -25.,
         -4.,  17., -67., -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,
         17., -67., -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,  17.,
        -67., -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,  17., -67.,
        -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,  17., -67., -46.,
        -25.,  -4.,  17., -67., -46., -25.,  -4.,  17., -67., -46., -25.,
         -4.,  17., -67., -46., -25.,  -4.,  17., -67., -46., -25.,  -4.,
         17.],
       [-65., -44., -23.,  -2.,  19., -65., -44., -23.,  -2.,  19., -65.,
        -44., -23.,  -2.,  19., -65., -44., -23.,  -2.,  19., -65., -44.,
        -23.,  -2.,  19., -65., -44., -23.,  -2.,  19., -65., -44., -23.,
         -2.,  19., -65., -44., -23.,  -2.,  19., -65., -44., -23.,  -2.,
         19., -65., -44

In [239]:
links

array([[[-1. , -0.5,  0. , ...,  0. ,  0.5,  1. ],
        [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
        [-1. , -1. , -1. , ..., -1. , -1. , -1. ]],

       [[-1. , -0.5,  0. , ...,  0. ,  0.5,  1. ],
        [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
        [-0.5, -0.5, -0.5, ..., -0.5, -0.5, -0.5]],

       [[-1. , -0.5,  0. , ...,  0. ,  0.5,  1. ],
        [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
        [ 0. ,  0. ,  0. , ...,  0. ,  0. ,  0. ]],

       [[-1. , -0.5,  0. , ...,  0. ,  0.5,  1. ],
        [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
        [ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5]],

       [[-1. , -0.5,  0. , ...,  0. ,  0.5,  1. ],
        [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ],
        [ 1. ,  1. ,  1. , ...,  1. ,  1. ,  1. ]]])

In [232]:
mus.shape

(5, 100)

In [218]:
np.tile(values_space[:, 2:], (belief_values.size, 1, 1)).reshape((belief_values.size, values_space[:, 2:].shape[0], values_space[:, 2:].shape[1]))

array([[[-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ],
        [-1. ],
        [-0.5],
        

In [221]:
links.T.shape

(3, 100, 5)

In [214]:
bvs

array([[-1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

In [194]:
links.shape

(5, 100, 3)

In [174]:
np.tile(values_space, (1, 1, 1)).shape

(1, 100, 3)

In [170]:
values_space.shape

(100, 3)

In [211]:
a = np.arange(15).reshape((5, 3)).astype(float)
print(a)

b = np.tile(np.array([10, -10, 4]), (3, 1, 1))
#print(b) 
d = np.tile(np.array([-1, -1/2, 1]), (5, 1))
#print(d)
c = np.tile(a, (3, 1)).reshape((3, 3, 5))
c[:, 1, :] = d.T
print(c)

#b @ c

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]
 [12. 13. 14.]]
[[[ 0.   1.   2.   3.   4. ]
  [-1.  -1.  -1.  -1.  -1. ]
  [10.  11.  12.  13.  14. ]]

 [[ 0.   1.   2.   3.   4. ]
  [-0.5 -0.5 -0.5 -0.5 -0.5]
  [10.  11.  12.  13.  14. ]]

 [[ 0.   1.   2.   3.   4. ]
  [ 1.   1.   1.   1.   1. ]
  [10.  11.  12.  13.  14. ]]]
